sudo: required

services:
  - docker

env:
  matrix:
    - TASK="docker-compose exec web pytest --cov=tests --disable-pytest-warnings"
    - TASK=""

before_script:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose up -d

script:
  - $TASK
